---
- name: Install the required packages
  hosts: all
  sudo: True
  vars:
    nodejs_version: 5.x
    ruby_version: 2.2
    dotfiles:
      - arangosh.rc
      - bundle
      - config
      - csirc
      - gemrc
      - gitconfig
      - irbrc
      - tmux.conf
      - tmuxinator
      - vimrc
      - zsh
      - zshrc
    apt_packages:
      - cargo-stable
      - cloc
      - git
      - git-svn
      - htop
      - imagemagick
      - jq
      - libpq-dev
      - neovim
      - nodejs
      - optipng
      - postgresql
      - redis-server
      - ruby{{ ruby_version }}
      - ruby{{ ruby_version }}-dev
      - ruby-switch
      - rust-stable
      - silversearcher-ag
      - tig
      - tmux
      - tree
      - vim
      - wget
      - zsh
    vim_packages:
      vim-pathogen: tpope/vim-pathogen
      vim-colors-solarized: altercation/vim-colors-solarized
      vim-polyglot: sheerun/vim-polyglot
      vim-fugitive: tpope/vim-fugitive
      vim-commentary: tpope/vim-commentary
      vim-dispatch: tpope/vim-dispatch
      vim-surround: tpope/vim-surround
      vim-repeat: tpope/vim-repeat
      vim-textobj-user: kana/vim-textobj-user
      vim-textobj-rubyblock: nelstrom/vim-textobj-rubyblock
      rainbow: luochen1990/rainbow
      syntastic: scrooloose/syntastic
      ctrlp.vim: ctrlpvim/ctrlp.vim
      vim-rspec: thoughtbot/vim-rspec
    npm_packages:
      - npm
      - jslint
      - jshint
      - jscs
      - elm
    ruby_gems:
      - bundler
      - tmuxinator
    marks:
      c: /home/vagrant/Code
    apt_keys:
      - 'http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc'
      - 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    apt_repositories:
      - 'deb http://packages.erlang-solutions.com/ubuntu vivid contrib'
      - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} vivid main'
      - 'ppa:hansjorg/rust'
      - 'ppa:brightbox/ruby-ng'
      - 'ppa:neovim-ppa/unstable'
  tasks:
    - name: Add APT Keys
      apt_key: url="{{ item }}"
      with_items: apt_keys
    - name: Add APT Repositories
      apt_repository: repo="{{ item }}" state=present
      with_items: apt_repositories
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe
    - name: Install missing packages
      apt: name={{ item }}
      with_items: apt_packages
    - name: Link Dotfiles
      file: path=/home/vagrant/.{{ item }} state=link src=/home/vagrant/Code/dotfiles/tilde/{{ item }}
      with_items: dotfiles
    - name: Install or update Vim plugins
      git: repo=https://github.com/{{ item.value }} dest=/home/vagrant/.vim/bundle/{{ item.key }}
      with_dict: vim_packages
    - name: Set default shell for Vagrant user
      user: name=vagrant shell=/bin/zsh
    - name: Set the timezone
      command: timedatectl set-timezone Europe/Berlin
    - name: Create the marks directory
      file: path=/home/vagrant/.marks state=directory
    - name: Configure the marks
      file: path=/home/vagrant/.marks/{{ item.key }} state=link src={{ item.value }}
      with_dict: marks
    - name: Create ~/.bin
      file: path=/home/vagrant/.bin state=directory owner=vagrant group=vagrant
    - name: Download icdiff
      get_url: url=https://raw.githubusercontent.com/jeffkaufman/icdiff/release-1.7.3/icdiff dest=/home/vagrant/.bin/icdiff owner=vagrant group=vagrant mode="u=rwx"
    - name: Download hub
      get_url: url=https://github.com/github/hub/releases/download/v2.2.2/hub-linux-amd64-2.2.2.tgz dest=/tmp/hub.tgz
    - name: Unarchive hub
      unarchive: src=/tmp/hub.tgz dest=/tmp copy=false
    - name: Move hub
      command: cp /tmp/hub-linux-amd64-2.2.2/bin/hub /home/vagrant/.bin/hub
    - name: Set owner, group and mode for hub
      file: path=/home/vagrant/.bin/hub owner=vagrant group=vagrant mode="u=rwx"
    - name: Switch to the correct Ruby version
      command: ruby-switch --set ruby{{ ruby_version }}
    - name: Install default Ruby gems
      command: gem install {{ item }}
      with_items: ruby_gems
    - name: Install default Ruby gems
      command: npm install -g {{ item }}
      with_items: npm_packages
